name: jreleaser
version: 0.7.0
summary: Release Java projects quickly and easily with JReleaser
description: |
  JReleaser is a release automation tool for Java projects. Its goal is to simplify creating releases
  and publishing artifacts to multiple package managers while providing customizable options.
  
  JReleaser takes inputs from popular builds tools (Ant, Maven, Gradle) such as JAR files, binary
  distributions (.zip, .tar), JLink images, or any other file that you’d like to publish as a Git
  release on popular Git services such as Github or Gitlab. Distribution files can additionally be
  published to be consumed by popular package managers as Homebrew, Snapcraft, or get ready to be
  launched via JBang. Releases may be announced in a variety of channels such as Twitter, Zulip, or SDKMAN!

grade: stable
confinement: strict
base: core18
type: app

apps:
  jreleaser:
    command: $SNAP/bin/jreleaser
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java/jre/"
      PATH: "$SNAP/bin:$PATH:$SNAP/usr/lib/jvm/java/jre/bin"
    plugs:
      - network
      - home

parts:
  jreleaser:
    plugin: dump
    source: https://github.com/jreleaser/jreleaser/releases/download/v0.7.0/jreleaser-0.7.0.tar
    source-checksum: sha256/bd4ce2b111df413c7f90fe1ed45418ee36d947803fe4ce0c9d3cfc1f3bab2604
    stage-packages:
      - curl
      - openjdk-8-jre
      - ca-certificates
      - ca-certificates-java
    organize:
      'usr/lib/jvm/java-8-openjdk*': 'usr/lib/jvm/java'
    prime:
      - -usr/lib/jvm/java/lib/security/cacerts
      - -usr/lib/jvm/java/jre/lib/security/cacerts