name: jreleaser
version: '0.2.0'
summary: Release Java projects quickly and easily with JReleaser
description: |
  Release Java projects quickly and easily with JReleaser

grade: stable
confinement: strict
base: core20
type: app

apps:
  jreleaser:
    command: $SNAP/bin/jreleaser
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java/jre/"
      PATH: "$SNAP/bin:$PATH:$SNAP/usr/lib/jvm/java/jre/bin"

parts:
  jreleaser:
    plugin: dump
    source: https://github.com/jreleaser/jreleaser/releases/download/v0.2.0/jreleaser-0.2.0.tgz
    source-checksum: sha256/5ea59f93dd44945d6b4cf82c3677b2a5b5a8ef88701d071ecbe143d98e6b6bf4
    build-packages:
      - wget
    stage-packages:
      - openjdk-8-jre
      - ca-certificates
      - ca-certificates-java
    organize:
      'jreleaser-0.2.0/bin': bin
      'jreleaser-0.2.0/lib': lib
      'usr/lib/jvm/java-8-openjdk*': 'usr/lib/jvm/java'
    prime:
      - -usr/lib/jvm/java/lib/security/cacerts
      - -usr/lib/jvm/java/jre/lib/security/cacerts