name: jreleaser
version: 0.3.0
summary: Release Java projects quickly and easily with JReleaser
description: |
  JReleaser is a release automation tool for Java projects. Its goal is to simplify creating releases
  and publishing artifacts to multiple package managers while providing customizable options.
  
  JReleaser takes inputs from popular builds tools (Ant, Maven, Gradle) such as JAR files, binary
  distributions (.zip, .tar), JLink images, or any other file that you’d like to publish as a Git
  release on popular Git services such as Github or Gitlab. Distribution files can additionally be
  published to be consumed by popular package managers as Homebrew, Snapcraft, or get ready to be
  launched via Jbang. Releases may be announced in a variety of channels such as Twitter, Zulip, or SDKMAN!

grade: stable
confinement: strict
base: core18
type: app

apps:
  jreleaser:
    command: bin/jreleaser
    environment:
      JAVA_HOME: "/usr/lib/jvm/java/jre/"
      PATH: "/bin:$PATH:/usr/lib/jvm/java/jre/bin"
    plugs:
      - network
      - home

parts:
  jreleaser:
    plugin: dump
    source: https://github.com/jreleaser/jreleaser/releases/download/v0.3.0/jreleaser-0.3.0.tar
    source-checksum: sha256/7ae48e0666170b0fb81800f7079231b87030e4f834903711b6c89be9f2cb65ce
    stage-packages:
      - curl
      - openjdk-8-jre
      - ca-certificates
      - ca-certificates-java
    organize:
      'usr/lib/jvm/java-8-openjdk*': 'usr/lib/jvm/java'
    prime:
      - -usr/lib/jvm/java/lib/security/cacerts
      - -usr/lib/jvm/java/jre/lib/security/cacerts
